volumes:
  postgres-data:


services:
  postgresql:
    container_name: postgresql
    image: postgres:15.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"