volumes:
  postgres-data:
  redis-data:


services:
  postgresql:
    container_name: postgresql
    image: postgres:15.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"

  redis:
    container_name: redis-tokens
    image: redis/redis-stack:6.2.6-v9
    env_file: .env
    volumes:
      - redis-data:/data
    restart: on-failure
    ports:
      - "6379:6379"
