"""Station model

Revision ID: 39c9cb8c488f
Revises: e09a1992a551
Create Date: 2023-11-11 12:37:57.159907

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '39c9cb8c488f'
down_revision = 'e09a1992a551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA stations")
    op.create_table('station',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('sid', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('sid'),
                    schema='stations',
                    comment='Table with all stations'
                    )
    op.create_index(op.f('ix_stations_station_sid'), 'station', ['sid'], unique=True, schema='stations')

    op.create_table('route',
                    sa.Column('node1_sid', sa.Integer(), nullable=True),
                    sa.Column('node2_sid', sa.Integer(), nullable=True),
                    sa.Column('length', sa.Integer, nullable=True),
                    sa.Column('sid', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['node1_sid'], ['stations.station.sid'], ),
                    sa.ForeignKeyConstraint(['node2_sid'], ['stations.station.sid'], ),
                    sa.PrimaryKeyConstraint('sid'),
                    schema='stations',
                    comment='Table with all stations'
                    )
    op.create_index(op.f('ix_stations_route_sid'), 'route', ['sid'], unique=True, schema='stations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stations_route_sid'), table_name='route', schema='stations')
    op.drop_table('route', schema='stations')
    op.drop_index(op.f('ix_stations_station_sid'), table_name='station', schema='stations')
    op.drop_table('station', schema='stations')
    op.execute("DROP SCHEMA stations")
    # ### end Alembic commands ###
